const Map<String, String> ar = {
  'Login': 'تسجيل دخول',
  'Logout': 'تسجيل خروج',
  'SignUp': 'تسجيل حساب جديد',
  'Email': 'البريد الالكتروني',
  'Password': 'الرقم السري',
  'change_language': 'تغيير اللغة',
  'add_planet': 'اضافة نبات',
  'myـPlanet': 'نباتاتي',
  'Add new Plant': 'اضافة نبتة جديدة',
  'Plant Name': 'اسم النبتة',
  'Sensor Number': 'رقم المستشعر',
  'Register here!': 'تسجيل من هنا !',
  'Sign in With Google': ' جوجل',
  'statistics': 'احصائيات',
  'Login here': 'سجل من هنا',
  'Already have an account ? ': 'هل لديك حساب ؟ ',
  'I will use email': 'سأستخدم البريد الإلكتروني',
  'Username': 'الاسم',
};
