name: green_plant
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  carousel_pro:
  transparent_image:
  flutter_spinkit:
  flutter_typeahead:
  uuid:
  splashscreen:

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.5
  firebase_database: "^6.0.0"

  get: ^4.1.4
  flutter_riverpod: ^0.13.0
  curved_navigation_bar: ^0.3.7
  font_awesome_flutter: ^9.0.0
  flutter_local_notifications: ^5.0.0+4

  google_sign_in: "^4.5.1"
  get_storage: ^2.0.2

  flutter_launcher_icons: ^0.9.0
  image_picker: ^0.7.5
  firebase_storage: ^8.0.6
  charts_flutter: ^0.10.0
  flutter_villains: ^1.2.1

  sqflite: ^1.3.2+1
  path: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/green1.png

